- name: Install chrony
  hosts: workers
  become: true
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Install Chrony package
      ansible.builtin.shell: apt install chrony
