- name: Join worker to cluster
  hosts: all          
  become: true
  tasks:
    - name: Get join command from master via delegate
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command
      delegate_to: 192.168.2.220    # master IP 직접 지정
      vars:
        ansible_user: root                                         
        ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_rsa   
      run_once: true

    - name: Execute join command on worker
      ansible.builtin.command: "{{ join_command.stdout }}"
