- name: Get join command from master
  hosts: all
  become: true
  tasks:
    - name: Generate join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command
      when: inventory_hostname == 'hks02-master'

    - name: Share join command as fact
      ansible.builtin.set_fact:
        join_cmd: "{{ join_command.stdout }}"
        cacheable: true
      when: inventory_hostname == 'hks02-master'

# Play 2: worker에서 join 실행
- name: Join worker to cluster
  hosts: all
  become: true
  tasks:
    - name: Execute join command
      ansible.builtin.command: "{{ hostvars['hks02-master']['join_cmd'] }}"
      when: inventory_hostname == 'npu_server'
