[master]
hks02-master ansible_host=192.168.2.10 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa

[workers]
npu_server ansible_host=192.168.2.105 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa
